version: "3"
services:
  client:
    image: "jordanlewis9/multi-client-multi-docker"
    mem_limit: 128m
    hostname: client
  server:
    image: "jordanlewis9/multi-server-multi-docker"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "jordanlewis9/multi-worker-multi-docker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "jordanlewis9/multi-nginx-multi-docker"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"