name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t jordanlewis9/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true jordanlewis9/react-test npm test

      - run: docker build -t jordanlewis9/multi-client-multi-docker ./client
      - run: docker build -t jordanlewis9/multi-nginx-multi-docker ./nginx
      - run: docker build -t jordanlewis9/multi-server-multi-docker ./server
      - run: docker build -t jordanlewis9/multi-worker-multi-docker ./worker

      - run: docker push jordanlewis9/multi-client-multi-docker
      - run: docker push jordanlewis9/multi-client-multi-docker
      - run: docker push jordanlewis9/multi-client-multi-docker
      - run: docker push jordanlewis9/multi-client-multi-docker